language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
- set -o pipefail
- travis_retry xcodebuild -workspace Calculator.xcworkspace -destination "platform=iOS Simulator,name=iPhone 6"
