
language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

before_install:
- rvm get head
- brew update
- brew outdated carthage || brew upgrade carthage

script:
- set -o pipefail
- travis_retry xcodebuild -workspace Calculator.xcworkspace -scheme "Calculator" -destination "platform=iOS Simulator,name=iPhone 6"
